### ISSUE TITLE
請問有辦法轉出精華區的資料嗎？

### ISSUE THREAD

**Issue by hydrogencl** [jk4837/BS2_Backup#1]
您好，謝謝您的程式，我成功轉出看版內的文章，但就是精華區的轉不出來，不知道您是否有意願寫轉精華區（有子資料夾的版本）？

**Comment by jk4837** [comment]
抱歉最近才看到，還有需要嗎?

**Comment by babylun** [comment]
您好，請問是否還有意願寫轉精華區(有子資料夾)的版本呢? 最近才把之前留存的.tgz檔案解開卻發現讀不了，看板跟信件都已成功轉出~謝謝

**Comment by jk4837** [comment]
@babylun  @babylun 
粗略完成一版了喔
有什麼建議可以提
